# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10P4rtdpdoXCADFolxqpQGHL2vsJtWpkw
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/healthcare_dataset (1).csv")
df.head()

billing = df.groupby(["Medical Condition","Insurance Provider"])["Billing Amount"].sum().unstack()
billing

plt.title("Billing Amount by Medical Condition and Insurance Provider")
plt.xlabel("Medical Condition")
plt.ylabel("Billing Amount")
plt.show()

billing.plot(
    kind = "bar",
    stacked = True,
    figsize = (10,6)
)