# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10P4rtdpdoXCADFolxqpQGHL2vsJtWpkw
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/healthcare_dataset (1).csv")
df.head()

billing = df.groupby(["Medical Condition","Insurance Provider"])["Billing Amount"].sum().unstack()
billing

plt.title("Billing Amount by Medical Condition and Insurance Provider")
plt.xlabel("Medical Condition")
plt.ylabel("Billing Amount")
plt.show()

billing.plot(
    kind = "bar",
    stacked = True,
    figsize = (10,6)
)

df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])

df['Admission Month'] = df['Date of Admission'].dt.to_period('M')


df['Admission Month']

monthly_admissions = df.groupby('Admission Month').size()
monthly_admissions

plt.figure(figsize=(12, 6))
monthly_admissions.plot(kind="line", marker="o")

plt.title("Monthly Patient Admission")
plt.xlabel("Month")
plt.ylabel("Admission Count")
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

correlation_matrix = df['Date of Admission']
df['Date of Admission']

df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])

df['Stay Duration'] = (df['Discharge Date'] - df['Date of Admission']).dt.days

correlation_matrix = df[['Age', 'Stay Duration', 'Billing Amount']].corr()
correlation_matrix

sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()